services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-local}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-local}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # EntryPoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls=true'

      # Dynamic config from files
      - '--providers.file.directory=/dynamic'
      - '--providers.file.watch=true'

      # Providers
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # API & Dashboard
      - '--api.dashboard=true'
      - '--api.insecure=false'

      # Observability
      - '--log.level=INFO'
      - '--accesslog=true'
      - '--metrics.prometheus=true'

    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - 'traefik.enable=true'

      # Dashboard router
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.hedgehog-inc.localhost`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.tls=true'

volumes:
  pgdata:
