services:
  db:
    ports:
      - '127.0.0.1:5432:5432'

  traefik:
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro
