import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	{
		ignores: [
			// Generated by better-auth (`pnpm auth:schema`) — не трогать руками
			'src/lib/server/db/auth.schema.ts',
			// shadcn-svelte generated components — excluded from lint
			'src/lib/components/ui/accordion/**',
			'src/lib/components/ui/avatar/**',
			'src/lib/components/ui/breadcrumb/**',
			'src/lib/components/ui/button/**',
			'src/lib/components/ui/dialog/**',
			'src/lib/components/ui/drawer/**',
			'src/lib/components/ui/dropdown-menu/**',
			'src/lib/components/ui/empty/**',
			'src/lib/components/ui/item/**',
			'src/lib/components/ui/kbd/**',
			'src/lib/components/ui/popover/**',
			'src/lib/components/ui/progress/**',
			'src/lib/components/ui/separator/**',
			'src/lib/components/ui/sheet/**',
			'src/lib/components/ui/skeleton/**',
			'src/lib/components/ui/slider/**',
			'src/lib/components/ui/tooltip/**'
		]
	},
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	}
);
